/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRegistrationRouteImport } from './routes/_authenticated/team-registration'
import { Route as AuthenticatedPlayerRegistrationRouteImport } from './routes/_authenticated/player-registration'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuctionControlRouteImport } from './routes/_authenticated/auction-control'
import { Route as AuthenticatedAuctionRouteImport } from './routes/_authenticated/auction'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRegistrationRoute =
  AuthenticatedTeamRegistrationRouteImport.update({
    id: '/team-registration',
    path: '/team-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayerRegistrationRoute =
  AuthenticatedPlayerRegistrationRouteImport.update({
    id: '/player-registration',
    path: '/player-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuctionControlRoute =
  AuthenticatedAuctionControlRouteImport.update({
    id: '/auction-control',
    path: '/auction-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuctionRoute = AuthenticatedAuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auction': typeof AuthenticatedAuctionRoute
  '/auction-control': typeof AuthenticatedAuctionControlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/player-registration': typeof AuthenticatedPlayerRegistrationRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auction': typeof AuthenticatedAuctionRoute
  '/auction-control': typeof AuthenticatedAuctionControlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/player-registration': typeof AuthenticatedPlayerRegistrationRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/auction': typeof AuthenticatedAuctionRoute
  '/_authenticated/auction-control': typeof AuthenticatedAuctionControlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/player-registration': typeof AuthenticatedPlayerRegistrationRoute
  '/_authenticated/team-registration': typeof AuthenticatedTeamRegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/auction'
    | '/auction-control'
    | '/dashboard'
    | '/player-registration'
    | '/team-registration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/auction'
    | '/auction-control'
    | '/dashboard'
    | '/player-registration'
    | '/team-registration'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/auction'
    | '/_authenticated/auction-control'
    | '/_authenticated/dashboard'
    | '/_authenticated/player-registration'
    | '/_authenticated/team-registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-registration': {
      id: '/_authenticated/team-registration'
      path: '/team-registration'
      fullPath: '/team-registration'
      preLoaderRoute: typeof AuthenticatedTeamRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/player-registration': {
      id: '/_authenticated/player-registration'
      path: '/player-registration'
      fullPath: '/player-registration'
      preLoaderRoute: typeof AuthenticatedPlayerRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auction-control': {
      id: '/_authenticated/auction-control'
      path: '/auction-control'
      fullPath: '/auction-control'
      preLoaderRoute: typeof AuthenticatedAuctionControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auction': {
      id: '/_authenticated/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuthenticatedAuctionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuctionRoute: typeof AuthenticatedAuctionRoute
  AuthenticatedAuctionControlRoute: typeof AuthenticatedAuctionControlRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlayerRegistrationRoute: typeof AuthenticatedPlayerRegistrationRoute
  AuthenticatedTeamRegistrationRoute: typeof AuthenticatedTeamRegistrationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuctionRoute: AuthenticatedAuctionRoute,
  AuthenticatedAuctionControlRoute: AuthenticatedAuctionControlRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlayerRegistrationRoute: AuthenticatedPlayerRegistrationRoute,
  AuthenticatedTeamRegistrationRoute: AuthenticatedTeamRegistrationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
