/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRegistrationRouteImport } from './routes/_authenticated/team-registration'
import { Route as AuthenticatedPlayerRegistrationRouteImport } from './routes/_authenticated/player-registration'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuctionRouteImport } from './routes/_authenticated/auction'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminAuctionRouteImport } from './routes/_authenticated/admin.auction'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRegistrationRoute =
  AuthenticatedTeamRegistrationRouteImport.update({
    id: '/team-registration',
    path: '/team-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayerRegistrationRoute =
  AuthenticatedPlayerRegistrationRouteImport.update({
    id: '/player-registration',
    path: '/player-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuctionRoute = AuthenticatedAuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuctionRoute =
  AuthenticatedAdminAuctionRouteImport.update({
    id: '/auction',
    path: '/auction',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auction': typeof AuthenticatedAuctionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/player-registration': typeof AuthenticatedPlayerRegistrationRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/admin/auction': typeof AuthenticatedAdminAuctionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auction': typeof AuthenticatedAuctionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/player-registration': typeof AuthenticatedPlayerRegistrationRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/admin/auction': typeof AuthenticatedAdminAuctionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/auction': typeof AuthenticatedAuctionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/player-registration': typeof AuthenticatedPlayerRegistrationRoute
  '/_authenticated/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/_authenticated/admin/auction': typeof AuthenticatedAdminAuctionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/auction'
    | '/dashboard'
    | '/player-registration'
    | '/team-registration'
    | '/admin/auction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/auction'
    | '/dashboard'
    | '/player-registration'
    | '/team-registration'
    | '/admin/auction'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/auction'
    | '/_authenticated/dashboard'
    | '/_authenticated/player-registration'
    | '/_authenticated/team-registration'
    | '/_authenticated/admin/auction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-registration': {
      id: '/_authenticated/team-registration'
      path: '/team-registration'
      fullPath: '/team-registration'
      preLoaderRoute: typeof AuthenticatedTeamRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/player-registration': {
      id: '/_authenticated/player-registration'
      path: '/player-registration'
      fullPath: '/player-registration'
      preLoaderRoute: typeof AuthenticatedPlayerRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auction': {
      id: '/_authenticated/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuthenticatedAuctionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auction': {
      id: '/_authenticated/admin/auction'
      path: '/auction'
      fullPath: '/admin/auction'
      preLoaderRoute: typeof AuthenticatedAdminAuctionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuctionRoute: typeof AuthenticatedAdminAuctionRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuctionRoute: AuthenticatedAdminAuctionRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAuctionRoute: typeof AuthenticatedAuctionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlayerRegistrationRoute: typeof AuthenticatedPlayerRegistrationRoute
  AuthenticatedTeamRegistrationRoute: typeof AuthenticatedTeamRegistrationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAuctionRoute: AuthenticatedAuctionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlayerRegistrationRoute: AuthenticatedPlayerRegistrationRoute,
  AuthenticatedTeamRegistrationRoute: AuthenticatedTeamRegistrationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
